### ISSUE TITLE
ManabeWaterVapor does not initialize the specific humidity correctly

### ISSUE THREAD

**Issue by brian-rose** [brian-rose/climlab#108]
The specific humidity diagnostic `q` is not properly set at initialization time:
```
import climlab
state = climlab.column_state()  # initialize temperatures
h2o = climlab.radiation.ManabeWaterVapor(state=state)
qinit = h2o.q.copy()  # keep a copy of the initial specific humidity
h2o.compute()  # compute the correct specific humidity for the current temperature
print(h2o.q - qinit)
```
produces
```
[-8.39713063e-05 -3.89167697e-05 -3.35535194e-05 -3.48322776e-05
 -3.84433691e-05 -4.27841482e-05 -4.86703517e-05 -5.60650540e-05
 -6.50215635e-05 -7.56321660e-05 -8.80011086e-05 -1.02225583e-04
 -1.18378618e-04 -1.36491166e-04 -1.56531917e-04 -1.78383921e-04
 -2.01817301e-04 -2.26457462e-04 -2.51748256e-04 -2.76909581e-04
 -3.00888926e-04 -3.22306366e-04 -3.39392570e-04 -3.49919351e-04
 -3.51122357e-04 -3.39615493e-04 -3.11296716e-04 -2.61244869e-04
 -1.83607255e-04 -7.14776984e-05]
```

Looking at the source code, the `_compute()` method is called at the end of the `__init__` method *of the parent class*, but this happens *before* the relative humidity profile is actually set correctly in the `ManabeWaterVapor` class.

This is a one line fix -- just add another call to `self._compute()` at the end of the `__init__` method for the daughter class.

**Comment by spencerahill** [comment]
For users, what is the simplest fix for this (i.e. without touching the climlab source code)?  I am using `ManabeWaterVapor` in a few places.

**Comment by brian-rose** [comment]
This only comes up if you are looking at the diagnostics prior to any timestepping calls.

The most straightforward workaround is to call either the `compute()` or `compute_diagnostics()` method. Best to call this on the top-level process object, as this will ensure that all the diagnostics are consistently calculated.

**Comment by brian-rose** [comment]
The difference between calling `compute()` and `_compute()` is that `compute()` handles the automatic recursion through all the nested subprocesses. It's not a good idea for the user to call `_compute()` directly unless they understand how the code works.
