### ISSUE TITLE
Server Offline for constants data?

### ISSUE THREAD

**Issue by pgierz** [brian-rose/climlab#116]
Hi,

I'm currently trying to use climlab, and the import hangs:

```
import numpy as np
import matplotlib.pyplot as plt
from climlab import constants as const
```

I assume that something is loaded in the constants module from some website, which might currently be offline?

**Comment by brian-rose** [comment]
Thanks for alerting us about this. Yes, it looks like the data server at http://thredds.atmos.albany.edu:8080/thredds/catalog.html
is offline at the moment. Hopefully @ktyle can get it back up without too much fuss.

FYI, the *first* time you import any part of climlab in a new installation, there will be an attempt to download and cache some data files. Further imports will use the local cache wherever possible, so you will be spared from misery due to a flaky server :-)

**Comment by brian-rose** [comment]
This should be fixed now! @pgierz please confirm that you can import climlab without hanging.

**Comment by pgierz** [comment]
Hi @brian-rose, seems to be working now as expected! Thanks :-)

One recommendation, maybe it would make sense to add some sort of timeout error? I guess that would need to happen [here](https://github.com/brian-rose/climlab/blob/f2a8ed16b89ec89e87340a2d421de183a4003c09/climlab/utils/data_source.py#L62):

https://github.com/brian-rose/climlab/blob/f2a8ed16b89ec89e87340a2d421de183a4003c09/climlab/utils/data_source.py#L62

or maybe further down in the actual function? Unfortunately I don't know the requests library so I don't know how to do that...
https://github.com/brian-rose/climlab/blob/f2a8ed16b89ec89e87340a2d421de183a4003c09/climlab/utils/data_source.py#L94-L100

**Comment by brian-rose** [comment]
Glad you're back on track!

Yes I agree that a graceful timeout error (and useful user feedback) would be appropriate for dealing with these server issues. I'll keep this issue open while we look into how to do that.

**Comment by pgierz** [comment]
It's apparently as easy as adding a `timeout=XXX` number to the `requests.get` command. I just sent you a pull request, hopefully it helps!

Best regards from Bremerhaven,
Paul

**Comment by brian-rose** [comment]
Many thanks, merged! Closing this now.

**Comment by phaustin** [comment]
Hi @brian-rose -- finishing up a port to jupyter-books on our ClimateLaboratoryBook fork.  It looks like the thredds url is down, can you confirm?  Would it be possible to share the nc files on google-drive/dropbox?  -thx, Phil

**Comment by ktyle** [comment]
Hi @phaustin I just restarted our thredds server. It's been acting a bit wonky of late; haven't dug into why just yet. Feel free to respond if you notice it becoming unresponsive again!

**Comment by phaustin** [comment]
thanks @brian-rose -- all good now
