### ISSUE TITLE
How to use the DailyInsolation class

### ISSUE THREAD

**Issue by spencerahill** [brian-rose/climlab#118]
I want to use `DailyInsolation` for a moist EBM run.  But from the docs I can't figure out its call signature.  How do I specify the day of year and other parameters that the `daily_insolation` function accepts?

I see from the source code that the `_daily_insolation_array` method includes the line `days_of_year = self.time['days_of_year']`.  But how/when does `self.time` get set?

Thanks!

**Comment by brian-rose** [comment]
Partial answer: `self.time` gets set during object initialization, see `climlab.process.TimeDependentProcess` here: 
https://github.com/brian-rose/climlab/blob/a8b628671b24845e54380163b5f4d5c73edc7ab2/climlab/process/time_dependent_process.py#L127

Like a lot of the internals, it's fairly hackish. The default is that the date is set to January 1. Time counters get updated at each timestep.

**Comment by brian-rose** [comment]
You might want to look at the code for the convenience class `climlab.model.EBM_seasonal` to see how it's set up.

https://github.com/brian-rose/climlab/blob/a8b628671b24845e54380163b5f4d5c73edc7ab2/climlab/model/ebm.py#L400

**Comment by spencerahill** [comment]
Thanks Brian.  I'm realizing that my use case is similar to the one from several months ago, i.e. #89 , where I'm actually interested in insolation at a fixed day of the year with now annual cycle progression.  Upon looking through my code I think I have what I need already to get that working.
