### ISSUE TITLE
Cannot step forward 2D seasonal EBM 

### ISSUE THREAD

**Issue by m-schillinger** [brian-rose/climlab#121]
Hello, I am trying to create an EBM_seasonal with 2D domain:

`state2d=climlab.surface_state(num_lat=90, num_lon=180)`
`model2d = climlab.model.ebm.EBM_seasonal(state=state2d)`
`model2d.step_forward()`

This fails in field.py with the error message ValueError: Cannot reconcile shapes of input_array and domain.

This is very similar to this issue here: https://github.com/brian-rose/climlab/issues/34, there the issue was closed and said to be fixed. It is true that the same code works with EBM_annual. But for the seasonal EBM it doesn't seem to be resolved?

I am very new to Climlab and climate science in general and appreciate any help. Thanks!

Version info: Python 3.7.4 and Climlab 0.7.5

--
Update: I checked the source code and in DailyInsolation, function _get_current_insolation it says as a comment "this probably only works for 1D (latitude) domains" . So seems to be known. Any ideas for fixes?

**Comment by brian-rose** [comment]
Thanks for this report! Yes it looks like this is a loose end that we never cleaned up.

I'll see if there's an easy fix.

In the bigger picture, this is yet another example of why we should be using xarray data structures in the internals, because it would make most of these multidimensional issues go away. #50

**Comment by brian-rose** [comment]
Looks like it was an easy fix. Assuming I didn't break anything and all the tests are passing, I will merge into master, and then probably release as a bug fix shortly.

**Comment by brian-rose** [comment]
This was fixed in #122.

**Comment by m-schillinger** [comment]
Thanks so much for fixing it so quickly!
