### ISSUE TITLE
Error installing climlab from source

### ISSUE THREAD

**Issue by aagarwal93** [brian-rose/climlab#127]
Dear Brian,

Firstly, thank you for creating this code package! It's been extremely easy and insightful in my learnings and research. I have reached a stage where I am trying to update the package for my research. I have been trying to install the package from source so that I can (eventually) make changes and re-install however, I have been having some issues.

I am following the instructions in the [installation guide](https://climlab.readthedocs.io/en/latest/installation.html) however, this has led to some compile errors in several Fortran scripts. I've attached the installation output in the file
[log.txt](https://github.com/brian-rose/climlab/files/5264857/log.txt). This is produced after running `pip install climlab`. The file is quite large, but the warnings seem to come from line 4668 onwards. This seems to build correctly, but in Python3.6, when importing climlab, I get a warning stating that the "RRTMG_SW module will not be functional". 

Any advice to fix this would be greatly appreciated!

**Comment by brian-rose** [comment]
There's a lot that can go wrong with building the Fortran components from source. I glanced through your build log and didn't see anything obvious.

Have you read through [the instructions on building from source here](https://climlab.readthedocs.io/en/latest/contributing.html#contributing-to-climlab)? I strongly recommend using conda to set up a complete reproducible build environment, as described in Method 2 on that page.

**Comment by aagarwal93** [comment]
Thanks for that direction - I managed to get this to work however, there are still issues upon using it. When importing climlab to python3.8, this leads to warnings that the RRTMG_LW and SW modules will not be functional. 

There are a number of warnings that arise when I run the pytest command, but I do not know exactly what's causing the RRTMG modules to not be functional. I've attached the output from the install command (
[log.pipinstall.txt](https://github.com/brian-rose/climlab/files/5279327/log.pipinstall.txt)) and the pytest command (
[log.pytest.txt](https://github.com/brian-rose/climlab/files/5279333/log.pytest.txt)
).

I think there may be an issue with compiling the Fortran code. There are some warnings for unused variables (I don't think these are important), but also a warning of "deprecated NumPy API" that could be causing a problem.

**Comment by brian-rose** [comment]
Your pytest log shows that all tests passed, so you have a fully functional climlab build! You can ignore all those warnings.

Make sure you're running climlab in the same conda environment you used to build in, as it includes all the runtime dependencies.
