### ISSUE TITLE
icelat diagnostics in asymetric EBM

### ISSUE THREAD

**Issue by m-kreuzer** [brian-rose/climlab#14]
The icelat diagnostic variable is not calculated correctly in an EBM that is not having symmetric solar distribution. 

In case one ice edge is at the pole but the other not, the `find_icelines` method of `climlab.surface.albedo.Iceline` class just detects the *none-pole* ice edge latitude.
This occured in an 'EBM_seasonal' in my case with a `StepFunctionAlbedo` ice albedo feedback in my case.

Here an ice edge plot for illustration:
![icelat_ebm_seasonal](https://cloud.githubusercontent.com/assets/16335796/14048265/7baf9a1c-f2ad-11e5-9fb2-a3bb351632eb.png)
(created by model: `climlab.EBM_seasonal(ai=0.6, Tf=-10)`)

Just wrote a small extension in the `find_icelines` method that fixes the bug. I will commit it to github and create a pull request.

**Comment by brian-rose** [comment]
Fixed in commit 1bae6d7 from @m-kreuzer
