### ISSUE TITLE
Unable to update to version 0.7.9

### ISSUE THREAD

**Issue by nfeldl** [brian-rose/climlab#142]
Hi Brian,

When I try to update climlab (`conda update climlab`) I'm only able to get 0.7.7.

Trying to force the latest version

```
conda install climlab=0.7.9
conda install -c conda-forge climlab=0.7.9
```

Returns

PackagesNotFoundError: The following packages are not available from current channels:

  - climlab=0.7.9

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

 A search of available packages `conda search -f climlab` only shows through 0.7.7.

**Comment by brian-rose** [comment]
Hi Nicole,

Yes! Unfortunately we ran into some problems with the build on conda-forge, see https://github.com/conda-forge/climlab-feedstock/pull/42. Wasn't able to figure it out and got distracted by other things.

If you want to use anything later than 0.7.7, for now at least, you have to build yourself. Instructions are here: https://climlab.readthedocs.io/en/latest/contributing.html#building-climlab-from-source

**Comment by brian-rose** [comment]
I recommend "Method 2" https://climlab.readthedocs.io/en/latest/contributing.html#method-2-using-conda-to-set-up-a-complete-build-environment

**Comment by brian-rose** [comment]
@nfeldl I'm happy to report that I finally got around the build problems on conda-forge.

You should now be able to do
```
conda install -c conda-forge climlab=0.7.10
```
as expected.

**Comment by brian-rose** [comment]
Closing this now, but feel free to reopen if you run into any more install problems.
