### ISSUE TITLE
Add a tutorial on spectral bands in RRTMG

### ISSUE THREAD

**Issue by brian-rose** [brian-rose/climlab#147]
Following the success of @AndrewWilliams3142 in implementing TOA spectral band output for RRTMG_LW, it would be great to get a tutorial notebook showing off how (and why) to use this feature. 

We can integrate the notebook into the climlab docs [here](https://climlab.readthedocs.io/en/latest/tutorial.html). To do this, we just put a new notebook into the [courseware directory](https://github.com/brian-rose/climlab/tree/main/courseware) at the root level of the repo, and then add a link on [this page in the doc source](https://github.com/brian-rose/climlab/blob/main/docs/source/tutorial.rst)

@AndrewWilliams3142 already has some great material for the tutorial in [this repo](https://github.com/AndrewWilliams3142/ECS_bump/blob/main/notebooks/spectral_lambda.ipynb). We could clean this up and remove the pyrads content for tutorial purposes.

**Comment by AndrewWilliams3142** [comment]
Allo allo! Yes happy to write up a tutorial notebook! I'll probably have some time next week to open a PR :)

**Comment by AndrewWilliams3142** [comment]
Hi @brian-rose , slight confusion on my end. I'm trying to build from source to get this new feature, but when I run `python -m pip install . --no-deps -vv` I get a long output which finally ends with this:

```
 ########### EXT COMPILER OPTIMIZATION ###########
  Platform      :
    Architecture: x64
    Compiler    : gcc

  CPU baseline  :
    Requested   : 'min'
    Enabled     : none
    Flags       : none
    Extra checks: none

  CPU dispatch  :
    Requested   : 'max -xop -fma4'
    Enabled     : none
    Generated   : none
  CCompilerOpt._cache_write[796] : write cache to path -> /tmp/pip-req-build-jkisghcu/build/temp.linux-x86_64-3.7/ccompiler_opt_cache_ext.py
  error: Command "gcc -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/users/andreww/miniconda3/envs/test_env/include -fPIC -Ibuild/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/climlab/convection/_emanuel_convection -I/tmp/pip-build-env-0zoqdc8b/overlay/lib/python3.7/site-packages/numpy/core/include -Ibuild/src.linux-x86_64-3.7/numpy/distutils/include -Iclimlab/radiation/cam3/src -I/home/users/andreww/miniconda3/envs/test_env/include/python3.7m -c build/src.linux-x86_64-3.7/climlab/convection/_emanuel_convection/_emanuel_convectionmodule.c -o build/temp.linux-x86_64-3.7/build/src.linux-x86_64-3.7/climlab/convection/_emanuel_convection/_emanuel_convectionmodule.o -MMD -MF build/temp.linux-x86_64-3.7/build/src.linux-x86_64-3.7/climlab/convection/_emanuel_convection/_emanuel_convectionmodule.o.d" failed with exit status 1
  Building wheel for climlab (PEP 517) ... error
  ERROR: Failed building wheel for climlab
Failed to build climlab
ERROR: Could not build wheels for climlab which use PEP 517 and cannot be installed directly
Exception information:
Traceback (most recent call last):
  File "/home/users/andreww/miniconda3/envs/test_env/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 180, in _main
    status = self.run(options, args)
  File "/home/users/andreww/miniconda3/envs/test_env/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 204, in wrapper
    return func(self, options, args)
  File "/home/users/andreww/miniconda3/envs/test_env/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 363, in run
    ", ".join(pep517_build_failure_names)
pip._internal.exceptions.InstallationError: Could not build wheels for climlab which use PEP 517 and cannot be installed directly
Removed build tracker: '/tmp/pip-req-tracker-zoti1x22'

**Comment by brian-rose** [comment]
Hi @AndrewWilliams3142, I don't think I've ever seen this one. Can you describe the build environment a little more:
- python version
- pip version
- compilers

I was wondering if there was a very recent update to pip that might have triggered this. I just tested the build procedure outlined [here in the docs](https://climlab.readthedocs.io/en/latest/contributing.html#method-2-using-conda-to-set-up-a-complete-build-environment) on MacOS 10.15.7 setting `python=3.9` and it worked normally. So basically I don't know.

I can try some tests on one of our linux servers.

**Comment by AndrewWilliams3142** [comment]
Python 3.7
pip 21.0.1

Not 100% sure how to check the compilers.. I'll retry again with `python=3.9` and see if that fixes it :)

**Comment by AndrewWilliams3142** [comment]
With python 3.9 it mostly works now. The only problem that on `import climlab` I get:

```
Downloading data from 'http://thredds.atmos.albany.edu:8080/thredds/fileServer/CLIMLAB/absorptivity/abs_ems_factors_fastvx.c030508.nc' to file '/home/users/andreww/.cache/pooch/a68348f124b8aeb936f98b2030344f8a-abs_ems_factors_fastvx.c030508.nc'.
/home/users/andreww/miniconda3/envs/test_env/lib/python3.9/site-packages/climlab/radiation/cam3/cam3.py:59: UserWarning: Cannot import and initialize compiled Fortran extension, CAM3 module will not be functional.
  warnings.warn('Cannot import and initialize compiled Fortran extension, CAM3 module will not be functional.')
```

But that doesn't matter for setting up the tutorial notebook.

**Comment by brian-rose** [comment]
@AndrewWilliams3142 I've just been testing this on a linux server. Python 3.7 vs 3.9 shouldn't matter AFAIK. I used Python 3.7 following exactly the procedure described [here](https://climlab.readthedocs.io/en/latest/contributing.html#method-2-using-conda-to-set-up-a-complete-build-environment):
```
conda create --name test_env python=3.7 --channel conda-forge
conda activate test_env
conda env update --file ./ci/requirements-linux.yml
python -m pip install . --no-deps -vv
```

The build succeeded normally.

HOWEVER I also see the same warning you describe above when I `import climlab`. This is a totally separate issue... apparently our THREDDS data server is offline again, which means that climlab can't find some required data files on first import.
http://thredds.atmos.albany.edu:8080/thredds/catalog.html

I'll have to bug @ktyle about this.

**Comment by brian-rose** [comment]
@AndrewWilliams3142 the server is back up again so hopefully you have smooth sailing.

If you encounter more data access problems, you can try pulling in the changes in #148 which changes the data paths to avoid that particular server. It seems to go offline frequently and needs babysitting.

**Comment by AndrewWilliams3142** [comment]
Sweet! I'm working on the notebook now, can probably put in a PR tomorrow or later this week. :)
