### ISSUE TITLE
Problems with ozone extrapolation

### ISSUE THREAD

**Issue by AndrewWilliams3142** [brian-rose/climlab#152]
Thought this was fixed in #140, but I just tried running [a ClimateLaboratoryBook tutorial](https://brian-rose.github.io/ClimateLaboratoryBook/courseware/water-water-everywhere.html) locally, with the latest `climlab` version, and I still get the same error:

```
Downloading data from 'http://www.atmos.albany.edu/facstaff/brose/resources/climlab_data/ozone/apeozone_cam3_5_54.nc' to file '/home/users/andreww/.cache/pooch/0e7ac27a9b97c3a843dcfdd7cd89a9b7-apeozone_cam3_5_54.nc'.
/home/users/andreww/miniconda3/envs/climlab/lib/python3.7/site-packages/climlab/radiation/radiation.py:156: UserWarning: Some grid points are beyond the bounds of the ozone file. Ozone values will be extrapolated.
  warnings.warn('Some grid points are beyond the bounds of the ozone file. Ozone values will be extrapolated.')
```

Perhaps my fix in #140 wasn't correct... I can take a closer look after tomorrow, just flagging it for now

**Comment by brian-rose** [comment]
I don't think that's an error! It's a warning message about extrapolating beyond the range of the source data. Expected whenever your pressure grid extends beyond 1004 hPa or 0.2842 hPa.

You would also get this message if you're interpolating onto a grid with latitude points poleward of 87.8638 degrees.

The warning is generated here: https://github.com/brian-rose/climlab/blob/ad9e0a9218de55f28ba6bf1d4d47c4b65ee0fce5/climlab/radiation/radiation.py#L156

**Comment by AndrewWilliams3142** [comment]
Aha! You're right! *wipes brow* I think in #140 is was an error because it was always getting extrapolated? I'd completely forgot that it should still raise a warning when extrapolating
