### ISSUE TITLE
`climlab` needs proper documentation

### ISSUE THREAD

**Issue by brian-rose** [brian-rose/climlab#17]
Almost goes without saying, but... `climlab` really needs a proper user manual.

Currently, usage is documented through a mix of inconsistent docstrings in the source code and worked out examples in the courseware notebooks. I'm sure new potential users will find this bewildering. 

Progress is forthcoming! @m-kreuzer is currently working on documentation for the EBM components of `climlab`. We hope to have comprehensive documentation online in summer 2016. Watch this space!

**Comment by rabernat** [comment]
How are you planning on doing the documentation? The standard choice would be [sphinx](http://www.sphinx-doc.org/en/stable/contents.html). This is what we use for xgcm. Then you can host your docs online with [readthedocs](https://readthedocs.org/). 

One nice thing about sphinx is [autodoc](http://www.sphinx-doc.org/en/stable/ext/autodoc.html), which can automatically convert docstrings into html documenation. Most python projects use this to document their API, since it is so convenient.

**Comment by brian-rose** [comment]
This is the approach that @m-kreuzer is using. We have a space reserved for climlab on [readthedocs](http://climlab.readthedocs.org). We'll hopefully get Moritz's work on the EBM documentation up there soon, and then extend it to cover the rest of climlab over the summer.

**Comment by m-kreuzer** [comment]
Yes I am working with Sphinx. Work is almost done (for the EBM parts),
which was my aim. Want to finish it soon.

Thanks for the suggestions anyway!

**Comment by brian-rose** [comment]
We are almost there. Just merged #22 from @m-kreuzer with all the detailed formatted docstrings needed for the sphinx-based documentation. Next we will merge the documentation itself, which is currently in a [separate repo](https://github.com/m-kreuzer/climlab-documentation).

**Comment by brian-rose** [comment]
With commit 9b8d5ce60c9969b35ba177dfc2acb3e394ddde7c I have merged the documentation from https://github.com/m-kreuzer/climlab-documentation into subfolder `docs` in the master branch of climlab.

Now to figure out how to get the documentation to show up on http://climlab.readthedocs.org/ ...

**Comment by rabernat** [comment]
I remember it was a pain in the ass with xgcm. Try to use conda for the RTD environment:

These might be useful templates
https://github.com/xgcm/xgcm/blob/master/readthedocs.yml
https://github.com/xgcm/xgcm/blob/master/doc/environment.yml
https://github.com/xgcm/xgcm/blob/master/doc/conf.py

**Comment by brian-rose** [comment]
Thanks @rabernat ! I'm passing the torch on to @cjcardinale to figure this one out...

**Comment by brian-rose** [comment]
And the docs are up, as of https://github.com/brian-rose/climlab/commit/505d30904b1d83136ddc7a7a4c803c9f729c2d5c!

http://climlab.readthedocs.io

**Comment by brian-rose** [comment]
We now need to focus on content. @m-kreuzer did a great job documenting the EBM but we need to catch up on other parts of the climlab functionality.

**Comment by brian-rose** [comment]
As of release v0.5.0, the docs are in much better shape in terms of coverage.

However the docs focus too much on climlab internals and not enough on the user interface. We should have simple working examples in the docs for every single process.

**Comment by rabernat** [comment]
Great work on the new release! Why not close this issue then and open a new, more specific one for the interface docs?

**Comment by brian-rose** [comment]
Good idea @rabernat.
