### ISSUE TITLE
TypeError when setting a state variable with an input ndarray of integers 

### ISSUE THREAD

**Issue by cjcardinale** [brian-rose/climlab#29]
Currently there is no conversion method from dtype(int) to dtype(float) when setting a state variable with a different input ndarray directly, or using model.set_state. I added code to 2 separate parts of **process.py** that converts int to float when using either of these methods. The conversion preserves the domain and I thought it was a better option than just adding a warning message. I will submit it in a pull request.

Below is code that raises the TypeError for both models "m" and "k".  I will use this code as a test.

`import climlab`
`from climlab.domain import initial`
`from climlab.domain.field import Field`
`state = initial.surface_state()`
`sfc = climlab.domain.zonal_mean_surface(num_lat=4)`
`state.Ts = Field([10,15,15,10],domain=sfc)`
`m = climlab.EBM(state=state)`
`m.step_forward()`

`k = climlab.EBM(num_lat=4)`
`k.set_state('Ts', Field([10,15,15,10], domain=k.domains['Ts']))`
`k.step_forward()`

**Error:**
> TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64')
    with casting rule 'same_kind'

**Comment by brian-rose** [comment]
Fixed in https://github.com/brian-rose/climlab/commit/b288538a3f3117e6a897724752be90734df94aca
