### ISSUE TITLE
climlab install

### ISSUE THREAD

**Issue by m-kreuzer** [brian-rose/climlab#3]
I have trouble with the install routine of climlab.

running *python setup.py install* in the climlab directory just copies the --init--.py file in the site-packages directory where python will access the package later.

This results in following error message after opening python (not in the climlab directory) and running *import climlab*

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/moritz/anaconda2/envs/env_numpy_1.10/lib/python2.7/site-packages/climlab-0.2.11-py2.7.egg/climlab/__init__.py", line 14, in <module>
>     from climlab.utils import constants
> ImportError: No module named utils

Right now I am managing either copying the rest of the files manually in the site-packages directory or running python from the climlab directory directly (no install needed).

**Comment by brian-rose** [comment]
Not sure what's going on here. I'll look into it.

**Comment by brian-rose** [comment]
Ok, I updated `setup.py` to use `find_packages()`, which automatically includes all the sub-modules within `climlab`. So running `python setup.py install` should work properly now. At least it did in my quick tests.

I also incremented version number to 0.2.12.

Thanks for your bug report!
