### ISSUE TITLE
`climlab.surface_state()` should produce both 1D and 2D domains

### ISSUE THREAD

**Issue by brian-rose** [brian-rose/climlab#32]
Currently there are two different methods for creating surface domains.

For a 1D domain in latitude:
```
import climlab
climlab.surface_state()
```
But for a 2D domain in latitude / longitude:
```
from climlab.domain import initial
initial.surface_state_2D()
```

It would be cleaner to have a single method `climlab.surface_state` that creates a 2D domain if the user passes a `num_lon` input argument.

**Comment by brian-rose** [comment]
This is fixed in https://github.com/brian-rose/climlab/commit/f6686e1ae99fcdd195386ca38ec2717b62ee4b19

`climlab.domain.initial.surface_state_2D` has been removed.

**Comment by brian-rose** [comment]
@cjcardinale I made an editorial decision here. You may need to modify your test scripts slightly to use `surface_state` instead of `surface_state_2D`.

**Comment by cjcardinale** [comment]
Okay, I will do that.
