### ISSUE TITLE
2D EBM not working

### ISSUE THREAD

**Issue by brian-rose** [brian-rose/climlab#34]
If I create a 2D lat/lon domain and use it to initialize an EBM:
```
import climlab
state = climlab.surface_state(num_lon=4)
m = climlab.EBM_annual(state=state)
```
then try to step it forward:
```
m.step_forward()
```
I get an error
```
/Users/Brian/climlab/climlab/model/ebm.pyc in _compute_heating_rates(self)
    194         insolation = self.subprocess['insolation'].insolation
    195         self.albedo = self.subprocess['albedo'].albedo
--> 196         self.ASR = (1-self.albedo) * insolation
    197         self.OLR = self.subprocess['LW'].OLR
    198         self.net_radiation = self.ASR - self.OLR

ValueError: operands could not be broadcast together with shapes (90,1) (90,4,1)
```

The `albedo` subprocess is not getting the right grid dimensions.

**Comment by brian-rose** [comment]
The problem arises in `class Field` in the `__new__` method, which is called to create a new `Field` variable for the albedo.

The current logic for handling mismatches between shapes of input array and domain is no good.

**Comment by brian-rose** [comment]
As of https://github.com/brian-rose/climlab/commit/950047906bac7d46c2853d1f12eb0709143ac56f the logic for `Field` creation is improved.

The EBM example above now fails with
```
/Users/Brian/anaconda/lib/python2.7/site-packages/numpy/linalg/linalg.pyc in solve(a, b)
    382     signature = 'DD->D' if isComplexType(t) else 'dd->d'
    383     extobj = get_linalg_error_extobj(_raise_linalgerror_singular)
--> 384     r = gufunc(a, b, signature=signature, extobj=extobj)
    385
    386     return wrap(r.astype(result_t, copy=False))

ValueError: solve: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (m,m),(m,n)->(m,n) (size 4 is different from 90)
```
So there's a problem with the diffusion process.

The expected behavior in this case is that we would have meridional diffusion along each longitude line independently.

**Comment by brian-rose** [comment]
I added the above example to the test suite. It is currently failing.

**Comment by cjcardinale** [comment]
There is also an issue with the insolation.  `m.subprocess['insolation'].insolation` is just an array of zeros when lon is given.  Since there is a silent fail when computing the insolation, I ran through the process manually and got an error: 
```
/Users/christophercardinale/Documents/climlab/climlab/domain/field.py in __new__(cls, input_array, domain)
    112                     return None
    113                 else:
--> 114                     raise ValueError('Cannot reconcile shapes of input_array and domain.')
    115         obj.domain = domain
    116         #  would be nice to have some automatic domain creation here if none given

ValueError: Cannot reconcile shapes of input_array and domain.
```

**Comment by brian-rose** [comment]
Silent fails are bad!

**Comment by brian-rose** [comment]
Update:
This error goes away if I set
```
m.subprocess.diffusion.use_banded_solver = True
```
in the above example. 

I then get diffusion along each longitude line independently as expected.

Why are we not using the band solver option by default?

**Comment by brian-rose** [comment]
as of https://github.com/brian-rose/climlab/commit/f273d9653b08e603529a1dd50eeb74dd5855d95b, we are now using `use_banded_solver = True` for all EBM instances.

The 2D EBM test is now passing.

**Comment by brian-rose** [comment]
So this is "working" now in the sense that we have meridional diffusion on a 2D domain. Closing this issue.
But of course what we really want is a flexible 2D diffusion operator.
