### ISSUE TITLE
Stepping a model forward produces an error after changing the albedo

### ISSUE THREAD

**Issue by cjcardinale** [brian-rose/climlab#36]
If I create a default EBM with a 1D lat domain,  changing the albedo subprocess produces a TypeError when integrating the model over any period of time.  Changing the diffusion and insolation subprocesses did not produce this error. 
```
import climlab
m=climlab.EBM()
from climlab.surface import albedo
m.add_subprocess('albedo', albedo.ConstantAlbedo(domains=m.domains['Ts'], **m.param))
m.integrate_years(10.)
```  
**Error:** 
```
/Users/christophercardinale/Documents/climlab/climlab/process/time_dependent_process.pyc in integrate_years(self, years, verbose)
    363                 # reset all values to zero
    364                 for varname, value in self.timeave.iteritems():
--> 365                     self.timeave[varname] = 0*value
    366             # adding up all values for each timestep
    367             for varname in self.timeave.keys():

TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
```
To work around this error, calling compute_diagnostics, step_forward or integrate_years prior to changing the albedo subprocess will allow the model to step forward with the changed albedo.
```
m=climlab.EBM()
m.compute_diagnostics()
m.add_subprocess('albedo', albedo.ConstantAlbedo(domains=m.domains['Ts'], **m.param))
m.integrate_years(10.)
```

**Comment by cjcardinale** [comment]
This problem is confined to integrating forward.  The problem is a result of the diagnostic 'icelat' having a datatype of NoneType.  When computing diagnostics before changing the albedo, the 'icelat' diagnostic is now an integer and the model can integrate forward, but the 'icelat' remains unchanged.
```
m=climlab.EBM()
m.compute_diagnostics()
m.add_subprocess('albedo', albedo.ConstantAlbedo(domains=m.domains['Ts'], **m.param))
m.integrate_years(10.)
m.icelat

array([-70.,  70.])
```
The constant albedo has no subprocess 'iceline', so there shouldn't be any 'icelat'.

**Comment by brian-rose** [comment]
Fixed in https://github.com/brian-rose/climlab/commit/a0bb9afd5444129963f618d4698ad6f3f4b11ea8
