### ISSUE TITLE
initializing EBM does not work with manually created domain

### ISSUE THREAD

**Issue by m-kreuzer** [brian-rose/climlab#6]
first creating a domain manually and calling the EBM.**init**() method does not work.

```
>>> surf = climlab.domain.zonal_mean_surface()
>>> model = climlab.EBM(domains=surf)
```

Generates Error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "climlab/model/ebm.py", line 96, in __init__
    P2Insolation(domains=sfc, **self.param))
UnboundLocalError: local variable 'sfc' referenced before assignment
```

Subprocess P2Insolation refers to domain _sfc_ which is only created if no domain and no state are present during EBM initialization

**Comment by brian-rose** [comment]
As of `climlab 0.3.0` (released today), the recommended (and supported) way to do this is to pass the `state` dictionary (which includes the `domain` info) rather than trying to pass the domain.

There is a new method `climlab.surface_state()` to automate this:
```
import climlab
mystate = climlab.surface_state()
model = climlab.EBM(state=mystate)
```

**Comment by brian-rose** [comment]
Closing this because initializing with state variable dictionaries is just more robust overall.
