### ISSUE TITLE
Add instructions on running unit tests?

### ISSUE THREAD

**Issue by dhhagan** [brian-rose/climlab#69]
Hi Brian,

I'm reviewing your paper for JOSS and thought it may be nice to add a quick few lines showing others how to run the unittests with pytest. I see they are in the `climlab/tests/` directory, but it took a bit of digging to find them! I could have also just missed where you listed them, and if so, close without issue. Thanks!

**Comment by brian-rose** [comment]
Agreed that some better instructions are needed here. I'll hopefully get this done this week. Thanks.

**Comment by brian-rose** [comment]
There is now a new section in the docs on [Building and Testing CLIMLAB](http://climlab.readthedocs.io/en/latest/contributing.html#building-and-testing-climlab) with explicit instructions.

**Comment by brian-rose** [comment]
Closing this as based on feedback from @dhhagan in https://github.com/openjournals/joss-reviews/issues/659.
