### ISSUE TITLE
installing climlab through pip

### ISSUE THREAD

**Issue by nschiraldi** [brian-rose/climlab#75]
When trying install climlab through pip (i.e. with pipenv install climlab) the install fails, I think this is due to numpy not being explicitly stated in the requirements somewhere?

Installing climlab…
Collecting climlab
  Downloading https://files.pythonhosted.org/packages/8f/2c/6b1c50b4df6b9477a4dcbbce56b380cd473bbae70fb820fa5ab42984eda8/climlab-0.7.0.tar.gz (20.4MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ns742711\AppData\Local\Temp\pip-install-zszlptid\climlab\setup.py", line 93, in <module>
        setup_package()
      File "C:\Users\ns742711\AppData\Local\Temp\pip-install-zszlptid\climlab\setup.py", line 85, in setup_package
        patch_gnu_fortran()
      File "C:\Users\ns742711\AppData\Local\Temp\pip-install-zszlptid\climlab\setup.py", line 18, in patch_gnu_fortran
        from numpy.distutils.fcompiler import gnu
    ModuleNotFoundError: No module named 'numpy'

    ----------------------------------------

Error:  An error occurred while installing climlab!
Command "python setup.py egg_info" failed with error code 1 in C:\Users\ns742711\AppData\Local\Temp\pip-install-zszlptid\climlab\

**Comment by brian-rose** [comment]
Building the fortran components from source with `pip install` is probably a nightmare, that's why I strongly recommend that users install with `conda`. It would be great to make binaries available through `pip install` ... anyone want to take this on?

**Comment by nschiraldi** [comment]
Ah I see... I can try to set aside some time to "nudge" this along, but not sure how much time it will take me.

**Comment by brian-rose** [comment]
I just tested pip install and found that it worked fine as long as I was installing into an environment that had all the right bits and pieces.

Specifically I did this, on Mac OSX:
```
conda create --name buildenv python=3.7 pip pydap xarray pytest numpy scipy gfortran_osx-64 future attrdict
conda activate buildenv
pip install climlab
```

This resulted in a successful build and install of climlab 0.7.1 [(the latest version available through pypi)](https://pypi.org/project/climlab/)

**Comment by brian-rose** [comment]
The environment creation step is a little simpler now. You should be able to build, install, and test climlab from the source repo as follows:
```
conda env create --file ./ci/requirements-py37-osx.yml
conda activate test_env
python -m pip install . --no-deps -vv
pytest --pyargs climlab
```

(or substitute other python versions / operating systems for `py37-osx`)

I need to get the developer documentation updated to reflect this.

**Comment by brian-rose** [comment]
The docs have been updated with much clearer and up-to-date information about how to build from source, and also what happens when you try to `pip install climlab`, e.g.
- https://climlab.readthedocs.io/en/latest/installation.html#installing-from-source
- https://climlab.readthedocs.io/en/latest/contributing.html#method-2-using-conda-to-set-up-a-complete-build-environment

Closing this now. But someday it would be nice to have pre-built binaries available for pip install.
