### ISSUE TITLE
Broadcasting error when specifying fixed insolation array for Radiation process

### ISSUE THREAD

**Issue by brian-rose** [brian-rose/climlab#90]
Inspired by #89, the following script tries to set up a 1D insolation array for a specific time of year, and set this as a fixed input to the RRTMG radiation process:
```
num_lat = 4; num_lev = 20   # grid size
day_of_year = 80.  # days since Jan 1
import climlab
import numpy as np
lat = np.linspace(-90., 90., num_lat)
state = climlab.column_state(num_lev=num_lev, lat=lat)
insolation = climlab.solar.insolation.daily_insolation(lat=lat, day=day_of_year)
rad = climlab.radiation.RRTMG(name='Radiation', state=state, insolation=insolation.values)
rad.step_forward()
```

It fails due to a broadcasting error:
```
error: failed in converting 20th argument `coszen' of _rrtmg_sw.climlab_rrtmg_sw to C/Fortran array
```

**Comment by brian-rose** [comment]
Looks like the problem is triggered here:
 https://github.com/brian-rose/climlab/blob/b60d8f0db132ac944cc1936aa7d2ad2c4f428f00/climlab/radiation/rrtm/rrtmg_sw.py#L150

Which multiplies a 1D array with shape (num_lat,) by a 2D array with shape (num_lat, 1), producing (according to numpy broadcasting rules) a 2D array with shape (num_lat, num_lat)

**Comment by brian-rose** [comment]
The long-term solution to these infuriating array dimension problems is to switch to xarray-based data structures for most of the climlab internals. 

This is the ultimate goal of #50.

**Comment by spencerahill** [comment]
Yes, definitely an example of where xarray would shine :)

In the meantime, as I mentioned in my comment #89, I'll try to get a PR in soon that fixes this within the current numpy-based framework.

**Comment by spencerahill** [comment]
>Which multiplies a 1D array with shape (num_lat,) by a 2D array with shape (num_lat, 1), producing (according to numpy broadcasting rules) a 2D array with shape (num_lat, num_lat)

To clarify, what is the desired shape?  `(num_lat, num_lat)`, or something else?

**Comment by brian-rose** [comment]
Sorry, I wasn't clear. The desired shape is `(num_lat, 1)` to match the shape of `self.Ts`.

This code is here mainly to cover the case where `num_lat > 1` and `self.coszen` is a scalar, for which the desired behavior is to broadcast `self.coszen` to every latitude point.

The result is then passed through `climlab.radiation.rrtm.utils._climlab_to_rrtm()` which flips the pressure axis.

I'm not sure why we're not calling `climlab.radiation.rrtm.utils._climlab_to_rrtm_sfc()` here instead. That seems be the correct conversion. Regardless, I believe that the `f2py` layer automatically squeezes out any singleton dimensions.

**Comment by spencerahill** [comment]
> not sure why we're not calling climlab.radiation.rrtm.utils._climlab_to_rrtm_sfc() 

Isn't it being called?  The original logic was ` _climlab_to_rrtm_sfc(self.coszen * np.ones_like(self.Ts))`

**Comment by brian-rose** [comment]
D'oh. Yes you are right of course. I must not be seeing straight today.

**Comment by spencerahill** [comment]
FYI, I tried simply overwriting the `coszen` attribute to be the desired shape, but the error persists:

```python
num_lat = 4; num_lev = 20   # grid size
lat = np.linspace(-90., 90., num_lat)

day_of_year = 80.  # days since Jan 1
insolation = climlab.solar.insolation.daily_insolation(lat=lat, day=day_of_year)

state = climlab.column_state(num_lev=num_lev, lat=lat)
rad = climlab.radiation.RRTMG(name='Radiation', state=state, insolation=insolation)
coszen = rad.coszen
rad.coszen = np.expand_dims(coszen, -1)
print(rad.coszen)
rad.step_forward()
```

Which results in:
```
Getting ozone data from /Users/shill/Dropbox/miniconda3/lib/python3.5/site-packages/climlab/radiation/data/ozone/apeozone_cam3_5_54.nc
[[0.00000000e+00]
 [2.77706000e-01]
 [2.77706018e-01]
 [3.58635357e-08]]
---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
<ipython-input-17-7fca4a5c235d> in <module>()
     10 rad.coszen = np.expand_dims(coszen, -1)
     11 print(rad.coszen)
---> 12 rad.step_forward()

[...] 

error: failed in converting 20th argument `coszen' of _rrtmg_sw.climlab_rrtmg_sw to C/Fortran array
```

**Comment by brian-rose** [comment]
As I mentioned over in #91 , the example at the top of this page is causing problems unrelated to the broadcasting error.

A better example looks like this:
```
num_lat = 4; num_lev = 20   # grid size
day_of_year = 80.  # days since Jan 1
import climlab
import numpy as np
lat = np.linspace(-80., 80., num_lat)
state = climlab.column_state(num_lev=num_lev, lat=lat)
insolation = climlab.solar.insolation.daily_insolation(lat=lat, day=day_of_year)
rad = climlab.radiation.RRTMG(name='Radiation', state=state, insolation=insolation.values)
rad.step_forward()
```

This issue is that the latitude array should not include the poles (-90, 90) because these are interpreted as cell centers.

**Comment by brian-rose** [comment]
A simple workaround that seems to actually WORK without any modification of climlab code:
```
num_lat = 4; num_lev = 20   # grid size
day_of_year = 80.  # days since Jan 1
import climlab
import numpy as np
lat = np.linspace(-80., 80., num_lat)
state = climlab.column_state(num_lev=num_lev, lat=lat)
insolation = climlab.solar.insolation.daily_insolation(lat=lat, day=day_of_year)
ins_values = insolation.values[..., np.newaxis]
rad = climlab.radiation.RRTMG(name='Radiation', state=state, insolation=ins_values)
rad.step_forward()
```

This works because now the input parameter `insolation` has the same array dimensions as `rad.Ts`
