### ISSUE TITLE
Bizarre segmentation fault for multi-dimensional RRTMG process

### ISSUE THREAD

**Issue by brian-rose** [brian-rose/climlab#95]
The following code is triggering a segfault with climlab 0.7.1 on Mac OSX:
```
import climlab
state = climlab.column_state(num_lev=30, num_lat=60, water_depth=10.)
rad = climlab.radiation.RRTMG(state=state)
rad.step_forward()
```

Oddly, the following code (based on `climlab.test.test_rrtm.test_multidim`) works as expected:
```
import climlab
state = climlab.column_state(num_lev=40, num_lat=3, water_depth=5.)
rad = climlab.radiation.RRTMG(state=state)
rad.step_forward()
```

The problem seems limited to climlab 0.7.1. I found that 0.7.0 and previous versions worked normally. Could this somehow be related to the `attrdict` package?

I can't think of any particular reason why changing the grid dimensions would trigger a failure...

Not clear if this is related to #94 or not.

**Comment by brian-rose** [comment]
Swapping `CAM3` for `RRTMG` seems to make the problem go away.

**Comment by brian-rose** [comment]
Some testing reveals a threshold. With `num_lev=30, num_lat=42` (or smaller), the code runs without error.

The error is triggered with `num_lev=30, num_lat=43` or higher.

**Comment by brian-rose** [comment]
Could this be an issue with memory allocation for the fortran `RRTMG_LW` and `RRTMG_SW` objects?

Why would the error appear suddenly in climlab 0.7.1? Change in compilers and libraries?

Ugh.

**Comment by brian-rose** [comment]
Workaround: use smaller grids.

This came up in trying to run code in the coursewares repository:
<https://github.com/brian-rose/ClimateModeling_courseware/blob/master/Lectures/Lecture15%20--%20Heat%20transport.ipynb>

I'm modifying this code to use smaller grids (for now).

**Comment by brian-rose** [comment]
Setting the option `ozone_file=None` for the `RRTMG` process also makes the problem go away.

So this is likely something to do with the ozone interpolation. But still not clear why it would be triggered for `RRTMG` and not for `CAM3`.

**Comment by brian-rose** [comment]
Indeed it seems that the problem is related to ozone interpolation. The interpolation that occurs in `climlab.radiation.radiation.default_absorbers()` uses `xarray.DataArray.interp_like()` since climlab v0.7.1

This interpolation returns `NaN` for grid points that are out of range.

The threshold value `num_lat=43` arises because the highest latitude points on this grid are outside the range of the ozone data file (most poleward point in the data file is ±87.8638)

So we are passing `NaN` values to the radiation codes at those latitudes.

Apparently `CAM3` is more graceful at accepting `NaN` input than `RRTMG`.

The question is now, what should the expected behavior be in this case? Issue a warning and set ozone to zero?

Or does it make more sense to change the default grid generation so that points poleward of 87.8638 degrees latitude are never included by default?

(Or both)

**Comment by brian-rose** [comment]
Prior to climlab v0.7.1, we called `scipy.interpolate.interp2d` directly to do the ozone interpolation.

The default behavior for this function seems to be to extrapolate to out-of-bounds grid points rather than to issue NaNs. So this is probably what was happening near the poles in climlab 0.7.0 and previous. And extrapolation (perhaps with a warning issued?) seems like a good solution here.

I think we can get the same behavior by passing some extra keyword arguments to the xarray `interp_like` method because it is actually using scipy under the hood.

**Comment by spencerahill** [comment]
Wow what a thorny one!  Nice detective work to track down the source.
