### ISSUE TITLE
climlab package is huge!

### ISSUE THREAD

**Issue by rabernat** [brian-rose/climlab#99]
We have added climlab to our pangeo-notebook docker image (see https://github.com/pangeo-data/pangeo-stacks/). Poking around, I noticed that the installed package footprint is huge! 128MB! For reference this is about twice the size of scipy. This is almost all due to the presence of a huge netCDF file in `radiation/data/ozone`.

It's probably not a great idea to store a huge binary file like that in git period. There are some alternative ways you could provide the data, such as triggering a download to a cache when a user imports the module which needs that data.

**Comment by brian-rose** [comment]
Great to see climlab included in this initiative! 

I've been aware of this "huge data file" issue for a while but never had much incentive to fix it...

@rabernat do you happen to have any examples you can point me toward that implement this kind of "download and cache on demand" strategy?

**Comment by brian-rose** [comment]
The local caching is important because I really want to avoid **requiring** a working internet connection every time a radiation model object is initialized.

**Comment by ktyle** [comment]
@brian-rose isn't caching-on-demand what Cartopy does when loading in Natural Earth shapefiles? https://scitools.org.uk/cartopy/docs/v0.16/matplotlib/feature_interface.html

**Comment by brian-rose** [comment]
> @brian-rose isn't caching-on-demand what Cartopy does when loading in Natural Earth shapefiles? https://scitools.org.uk/cartopy/docs/v0.16/matplotlib/feature_interface.html

Could be! I've never looked at the Cartopy source. I'll check it out.

**Comment by brian-rose** [comment]
Yep, looks like the "download and cache" functionality is implemented in `cartopy.io.Downloader`:
https://github.com/SciTools/cartopy/blob/45d0479abed27f73c5bb8bac35036772a3faa773/lib/cartopy/io/__init__.py#L86

**Comment by brian-rose** [comment]
With #100 the installed package footprint is down to 15 MB.
